export  default interface UserModel {
  id: number,
  name: string,
  surname: string,
  additionalName: string,
  birthday: string,
  gender: string,
  placeOfStay: string,
  citizenship_country: string,
  city: string,
  docType: string,
  docSeriesNum: string,
  docDateOfIssue: string,
  docDateOfExpiry: string,
  rightToStay: string,
  ruDocSeries: string,
  ruDocNum: string,
  ruDocDateOfIssue: string,
  ruDocDateOfExpiry: string,
  migCardSeries: string,
  migCardNum: string,
  purposeOfComing: string,
  profession: string,
  dateOfEntryToRu: string,
  deadlineLiveInRu: string
}
